# Copyright 2025 Stefan Eissing (https://dev-icing.de)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: OpenSSL-1.0.2

'on':
  push:
    branches:
      - master
      - '*/ci'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  MARGS: "-j5"
  CFLAGS: "-g"

jobs:
  linux:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: openssl 1.0.2
            install_packages:
            install_steps:

    steps:
      - name: 'install prereqs'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-suggests --no-install-recommends \
            libtool autoconf automake pkgconf apache2 apache2-dev openssl \
            curl nghttp2-client libssl-dev libjansson-dev libcurl4-openssl-dev \
            ${{ matrix.build.install_packages }}
          python3 -m venv $HOME/venv

      - uses: actions/checkout@v4

      - name: 'install test prereqs'
        run: |
          [ -x "$HOME/venv/bin/activate" ] && source $HOME/venv/bin/activate
          python3 -m pip install -r test/requirements.txt

      - name: 'cache openssl'
        uses: actions/cache@v4
        id: cache-openssl
        env:
          cache-name: cache-openssl
        with:
          path: ~/openssl
          key: ${{ runner.os }}-build-${{ env.cache-name }}-1.0.2

      - name: 'install openssl'
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        run: |
          curl -LO https://github.com/openssl/openssl/releases/download/OpenSSL_1_0_2/openssl-1.0.2.tar.gz
          tar xfz openssl-1.0.2.tar.gz
          cd openssl-1.0.2
          CFLAGS="-fPIC" ./config --prefix=$HOME/openssl --libdir=lib
          make
          make -j1 install_sw

      - name: 'configure'
        # configure without --enable-werror since openssl 1.0.2 will give warnings
        run: |
          autoreconf -fi
          ./configure --with-openssl=$HOME/openssl

      - name: 'build'
        run: make V=1

